version: 0.10.0.{build}
image: Visual Studio 2022

clone_script:
- cmd: >-
    git clone -v --branch=develop --recursive --progress https://github.com/wowmodelviewer/wowmodelviewer.git C:\projects\wowmodelviewer

install:
- cmd: set PATH=C:\tools\vcpkg;%PATH%
- ps: C:\projects\wowmodelviewer\scripts\setup_x64_deps.ps1 -RepoRoot C:\projects\wowmodelviewer

before_build:
- cmd: >-
    call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" &&
    cmake --preset x64-Release -DBUILDNUMBER=%APPVEYOR_BUILD_NUMBER%

build_script:
- cmd: >-
    call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" &&
    cmake --build --preset x64-Release &&
    cd C:\projects\wowmodelviewer\bin &&
    ren WMV_Installer.exe WMV_Installer_v%APPVEYOR_BUILD_VERSION%.exe

test: off

artifacts:
- path: bin\WMV_Installer_v%APPVEYOR_BUILD_VERSION%.exe

for:
-
  branches:
    only:
      - develop

  on_success:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 success $env:WEBHOOK_URL
  on_failure:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 failure $env:WEBHOOK_URL
