/* This file was generated by syncqt. */
#ifndef QT_QTQMLDEBUG_VERSION_H
#define QT_QTQMLDEBUG_VERSION_H

#define QTQMLDEBUG_VERSION_STR "5.12.3"

#define QTQMLDEBUG_VERSION 0x050C03

#endif // QT_QTQMLDEBUG_VERSION_H
