set(WOWMV_SOURCES  AnimationExportChoiceDialog.cpp
                   animcontrol.cpp
                   AnimExporter.cpp
                   app.cpp
                   AVIGenerator.cpp
                   camera.cpp
                   charcontrol.cpp
                   CharDetailsFrame.cpp
                   DisplaySettings.cpp
                   effects.cpp
                   ExportSettings.cpp
                   filecontrol.cpp
                   GeneralSettings.cpp
                   imagecontrol.cpp
                   ItemImporterDialog.cpp
                   itemselection.cpp
                   lightcontrol.cpp
                   liquid.cpp
                   maptile.cpp
                   modelbankcontrol.cpp
                   modelcanvas.cpp
                   modelcontrol.cpp
                   modelviewer.cpp
                   NPCImporterDialog.cpp
                   Quantize.cpp
                   SettingsControl.cpp
                   shaders.cpp
                   UserSkins.cpp
                   util.cpp)