/* This file was generated by syncqt. */
#ifndef QT_QTOPENGL_VERSION_H
#define QT_QTOPENGL_VERSION_H

#define QTOPENGL_VERSION_STR "5.12.3"

#define QTOPENGL_VERSION 0x050C03

#endif // QT_QTOPENGL_VERSION_H
